### ISSUE TITLE
scotty-cookie no longer builds with scotty >= 0.20

### ISSUE THREAD

**Issue by jhrcek** [mmartin/scotty-cookie#1]
Hello,
today I was trying to build this package with recent version of scotty-0.22 and the package no longer builds.
It seems that scotty-0.20 removed the ScottyError typeclass (viz scotty [changelog](https://hackage.haskell.org/package/scotty-0.22/changelog))

This leads to following errors when compiling this package
```
scotty            > Registering library for scotty-0.22..
scotty-cookie     > configure
scotty-cookie     > Configuring scotty-cookie-0.1.0.3...
scotty-cookie     > build with ghc-9.8.2
scotty-cookie     > Preprocessing library for scotty-cookie-0.1.0.3..
scotty-cookie     > Building library for scotty-cookie-0.1.0.3..
scotty-cookie     > [1 of 1] Compiling Web.Scotty.Cookie
scotty-cookie     >          
scotty-cookie     > /tmp/stack-90435db138c932d8/scotty-cookie-0.1.0.3/src/Web/Scotty/Cookie.hs:68:24: error: [GHC-76037]
scotty-cookie     >     Not in scope: type constructor or class ‘ScottyError’
scotty-cookie     >    |     
scotty-cookie     > 68 | setCookie :: (Monad m, ScottyError e)
scotty-cookie     >    |                        ^^^^^^^^^^^
scotty-cookie     >          
scotty-cookie     > /tmp/stack-90435db138c932d8/scotty-cookie-0.1.0.3/src/Web/Scotty/Cookie.hs:75:30: error: [GHC-76037]
scotty-cookie     >     Not in scope: type constructor or class ‘ScottyError’
scotty-cookie     >    |     
scotty-cookie     > 75 | setSimpleCookie :: (Monad m, ScottyError e)
scotty-cookie     >    |                              ^^^^^^^^^^^
scotty-cookie     >          
scotty-cookie     > /tmp/stack-90435db138c932d8/scotty-cookie-0.1.0.3/src/Web/Scotty/Cookie.hs:82:24: error: [GHC-76037]
scotty-cookie     >     Not in scope: type constructor or class ‘ScottyError’
scotty-cookie     >    |     
scotty-cookie     > 82 | getCookie :: (Monad m, ScottyError e)
scotty-cookie     >    |                        ^^^^^^^^^^^
scotty-cookie     >          
scotty-cookie     > /tmp/stack-90435db138c932d8/scotty-cookie-0.1.0.3/src/Web/Scotty/Cookie.hs:89:25: error: [GHC-76037]
scotty-cookie     >     Not in scope: type constructor or class ‘ScottyError’
scotty-cookie     >    |     
scotty-cookie     > 89 | getCookies :: (Monad m, ScottyError e)
scotty-cookie     >    |                         ^^^^^^^^^^^
scotty-cookie     >          
scotty-cookie     > /tmp/stack-90435db138c932d8/scotty-cookie-0.1.0.3/src/Web/Scotty/Cookie.hs:95:27: error: [GHC-76037]
scotty-cookie     >     Not in scope: type constructor or class ‘ScottyError’
scotty-cookie     >    |     
scotty-cookie     > 95 | deleteCookie :: (Monad m, ScottyError e)
```

**Comment by mmartin** [comment]
Hi Jan,
Unfortunately, this package is unmaintained, as I no longer use Scotty (or Haskell for that matter).
If you are interested, I can transfer the ownership of this package to you.

**Comment by mmartin** [comment]
I just realized that this package has been merged directly into Scotty itself since last year.
So you should be good to go just by removing this package from your dependencies.
